### ISSUE TITLE
cannot configure

### ISSUE THREAD

**Issue by Istoleyourface** [tajas20006/neko2020#138]
self explanetory

**Comment by tajas20006** [comment]
@Istoleyourface 
thank you for raising the issue.

Could you tell me where you are placing the config file and which config you are trying to change.
I checked the latest exe and I could change the offset of my neko just fine.

![neko_below_cursor](https://github.com/tajas20006/neko2020/assets/28689137/16690a7e-ce8a-4e24-b958-8997ac7d262a)
![neko_besides_cursor](https://github.com/tajas20006/neko2020/assets/28689137/946e0e23-3707-468a-934b-0ba4139d5213)
![neko_on_cursor](https://github.com/tajas20006/neko2020/assets/28689137/126d67c2-1e5d-4d59-8a71-b458431ce01b)

**Comment by Istoleyourface** [comment]
hey, thanks for the response
the config file was ".configneko2020config.yml", under my %USERDATA% folder, as suggested in the readme.
but from your screenshots i can see that its meant to be a path.
i think the readme should be changed to say that its meant to be in a folder
![image](https://github.com/tajas20006/neko2020/assets/42488674/1f62edc0-0068-451b-bd8b-04557c1f46bd)

**Comment by tajas20006** [comment]
Oh, i didn't notice that. Sorry for the inconvenience.

It must have slipped through when updating the readme.
I will fix it.

**Comment by tajas20006** [comment]
![image](https://github.com/tajas20006/neko2020/assets/28689137/176c104d-1d73-4f50-bf6a-b9ad8c0706af)

updated!
