### ISSUE TITLE
[feature request] Add ability to hide/refresh neko while keeping the program running

### ISSUE THREAD

**Issue by GhostScript0r** [tajas20006/neko2020#141]
It would be good if there's an option to show/hide neko from the system tray menu, so that I don't have to stop and restart the program. Adding an option to change neko behavior immediately after changing the config would also be nice.

**Comment by tajas20006** [comment]
@GhostScript0r 
Thank you for the PR.

I've added some menus in the system tray.

- `Start`/`Stop` to show/hide neko.
- `Restart` to apply new config.

Take a look at it.
You can run the script with `poetry run python -m neko2020`.
If you like it, I'm gonna merge it.

#142

**Comment by tajas20006** [comment]
I merged this anyway.
If you have any further requests, raise another issue.
Thank you!
